### ISSUE TITLE
Add commands for full Hue API utilization

### ISSUE THREAD

**Issue by claytonjn** [infofiend/Hue-Lights-Groups-Scenes#9]
Allow SmartApps such as Rule Machine custom commands to utilize the full Hue API. These additional (non-SmartThings standard) commands include:
- alert
- bri_inc
- sat_inc
- hue_inc
- ct_inc
- xy_inc

**Comment by infofiend** [comment]
Except for xy values -- which I haven't added into the device types, this functionality already exists.  The following custom commands can already be created in Rule Machine for Bulbs and Groups:

on()
off()
poll()
setLevel()
setHue()
setSaturation()
setColor()
setColorTemperature()
setAdjustedColor()
setTT() -- transition time
reset()
refresh()

**Comment by infofiend** [comment]
I should have explained that Rule Machine -- and other SmartApps automatically have access to any of the functions of any device.

**Comment by claytonjn** [comment]
With the exception of Transition Time, all of those are default SmartThings commands. The ones I listed (i.e. alert) are Hue API commands. None of the commands I listed above from the Hue API are implemented yet. I don't know that anyone would want to use most of them, but I can definitely see people wanting to use alert with Rule Machine.

**Comment by infofiend** [comment]
I can certainly add alert, colormode, and effect (which is just a color loop).

Wondering why you want devices to have both setLevel & bri, both setSaturation & sat, or both setHue & hue functions.  Seems kinda repetitive, but maybe I’m missing something...

____________ 
Anthony Pastor

On March 23, 2016 at 4:18:03 PM, claytonjn (notifications@github.com) wrote:

With the exception of Transition Time, all of those are default SmartThings commands. The ones I listed (i.e. alert) are Hue API commands. None of the commands I listed above from the Hue API are implemented yet. I don't know that anyone would want to use most of them, but I can definitely see people wanting to use alert with Rule Machine.

**Comment by infofiend** [comment]
Ok, I'm an idiot.  I see those are incremental values.

**Comment by claytonjn** [comment]
I actually already added colorloop in the development branch I added. I need to test everything when I get home, but barring any issues I can merge that stuff. 

Yeah, like I said, I really only see people using alert. And colormode just for Circadian Daylight functionality. The others I figured it wouldn't hurt to have, just to have the full API functionality, but I don't really see use cases for them, and some (bri_inc) are duplicates of standard SmartThings commands.

**Comment by claytonjn** [comment]
Alert added in claytonjn-development branch.

**Comment by claytonjn** [comment]
Bri_inc added in claytonjn-development branch.

**Comment by claytonjn** [comment]
Sat_inc added in claytonjn-development branch.

**Comment by claytonjn** [comment]
Hue_inc added in claytonjn-development branch.

**Comment by claytonjn** [comment]
Ct_inc added in claytonjn-development branch.

**Comment by claytonjn** [comment]
Xy_inc added in claytonjn-development branch. I'll merge to master after I get home and test that all functionality still works.
